server.port=6005
spring.application.name=geo-portal
server.address=0.0.0.0
#security.ignored=/**

spring.jpa.show-sql=true
spring.datasource.hibernate.dialect=org.hibernate.dialect.SQLServer2019Dialect
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.main.allow-bean-definition-overriding=true
#springdoc.swagger-ui.path=/swagger-ui
logging.level.org.springframework=DEBUG

##################dev with localhost
spring.datasource.url=jdbc:sqlserver://192.168.254.90:1433;databaseName=ERPNewLatest;sendTimeAsDateTime=false;encrypt=false;trustServerCertificate=false;
spring.datasource.username=sa
spring.datasource.password=_d@F:=:0d1L(^)1D#_

#relm-name=demo
#spring.security.oauth2.resourceserver.jwt.issuer-uri=https://auth0.diu.edu.bd/realms/${relm-name}

##################################### diu #######################
#spring.datasource.url=jdbc:sqlserver://192.168.10.201:1433;databaseName=erp;sendTimeAsDateTime=false;encrypt=false;trustServerCertificate=false;
#spring.datasource.username=umsystem
#spring.datasource.password=umsystem

